import os
import re
import shutil
import subprocess
from pathlib import Path
from typing import Dict, Any, Optional

# Extension mappings for programming languages
LANGUAGE_EXTENSIONS = {
    "python": ".py",
    "py": ".py",
    "javascript": ".js",
    "js": ".js",
    "typescript": ".ts",
    "ts": ".ts",
    "cpp": ".cpp",
    "c++": ".cpp",
    "c": ".c",
    "java": ".java",
    "html": ".html",
    "css": ".css",
    "rust": ".rs",
    "rs": ".rs",
    "go": ".go",
    "golang": ".go",
    "csharp": ".cs",
    "c#": ".cs",
    "cs": ".cs",
    "php": ".php",
    "ruby": ".rb",
    "rb": ".rb",
    "kotlin": ".kt",
    "sql": ".sql",
    "shell": ".sh",
    "bash": ".sh"
}

# Workspace directory where created files will live
WORKSPACE_DIR = Path(__file__).resolve().parent.parent.parent / "workspace"


def get_vscode_executable() -> Optional[str]:
    """Find the VS Code executable on Windows."""
    for name in ["code", "code.cmd", "code.exe"]:
        found = shutil.which(name)
        if found:
            return found

    local_app_data = os.environ.get("LOCALAPPDATA", "")
    program_files = os.environ.get("ProgramFiles", "")
    program_files_x86 = os.environ.get("ProgramFiles(x86)", "")

    candidate_paths = [
        os.path.join(local_app_data, "Programs", "Microsoft VS Code", "Code.exe"),
        os.path.join(local_app_data, "Programs", "Microsoft VS Code", "bin", "code.cmd"),
        os.path.join(program_files, "Microsoft VS Code", "Code.exe"),
        os.path.join(program_files, "Microsoft VS Code", "bin", "code.cmd"),
        os.path.join(program_files_x86, "Microsoft VS Code", "Code.exe"),
        os.path.join(program_files_x86, "Microsoft VS Code", "bin", "code.cmd"),
    ]

    for p in candidate_paths:
        if os.path.exists(p):
            return p

    return None


def generate_code_content(language: str, task: str) -> str:
    """Generate high-quality, production-ready code template for the requested language and task."""
    lang = (language or "python").lower().strip()
    norm_task = (task or "").lower().strip()
    task_title = task.title() if task else "Program"

    # 1. Python Templates
    if lang in ["python", "py"]:
        if any(w in norm_task for w in ["sum", "add", "addition", "plus"]):
            return '''"""
Sum Calculator Program in Python
Generated by SADIE AI Assistant
"""

def calculate_sum(a: float, b: float) -> float:
    """Returns the sum of two numbers."""
    return a + b


def main():
    print("=" * 40)
    print("        SADIE PYTHON SUM CALCULATOR")
    print("=" * 40)
    
    try:
        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))
        result = calculate_sum(num1, num2)
        print(f"\\n✅ Result: {num1} + {num2} = {result}")
    except ValueError:
        print("\\n⚠️ Invalid input. Please enter valid numbers.")


if __name__ == "__main__":
    main()
'''
        elif any(w in norm_task for w in ["fibonacci", "fib"]):
            return '''"""
Fibonacci Series Generator in Python
Generated by SADIE AI Assistant
"""

def generate_fibonacci(n: int) -> list:
    """Generates the first n Fibonacci numbers."""
    if n <= 0:
        return []
    if n == 1:
        return [0]
    
    fib = [0, 1]
    while len(fib) < n:
        fib.append(fib[-1] + fib[-2])
    return fib


def main():
    print("=" * 40)
    print("      FIBONACCI SERIES GENERATOR")
    print("=" * 40)
    
    try:
        count = int(input("Enter number of terms: "))
        series = generate_fibonacci(count)
        print(f"\\nFibonacci Series ({count} terms):")
        print(" -> ".join(map(str, series)))
    except ValueError:
        print("Please enter a valid integer.")


if __name__ == "__main__":
    main()
'''
        elif any(w in norm_task for w in ["calc", "calculator"]):
            return '''"""
Interactive Multi-Operation Calculator in Python
Generated by SADIE AI Assistant
"""

def add(x: float, y: float) -> float:
    return x + y

def subtract(x: float, y: float) -> float:
    return x - y

def multiply(x: float, y: float) -> float:
    return x * y

def divide(x: float, y: float) -> float:
    if y == 0:
        raise ZeroDivisionError("Cannot divide by zero.")
    return x / y


def main():
    print("=" * 45)
    print("        SADIE ADVANCED CALCULATOR")
    print("=" * 45)
    print("Operations: [1] Add  [2] Subtract  [3] Multiply  [4] Divide")
    
    choice = input("Select operation (1/2/3/4): ").strip()
    try:
        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))
        
        if choice == "1":
            print(f"Result: {num1} + {num2} = {add(num1, num2)}")
        elif choice == "2":
            print(f"Result: {num1} - {num2} = {subtract(num1, num2)}")
        elif choice == "3":
            print(f"Result: {num1} * {num2} = {multiply(num1, num2)}")
        elif choice == "4":
            print(f"Result: {num1} / {num2} = {divide(num1, num2)}")
        else:
            print("Invalid operation choice.")
    except Exception as e:
        print(f"Error: {e}")


if __name__ == "__main__":
    main()
'''
        else:
            return f'''"""
{task_title}
Generated by SADIE AI Assistant
"""

def execute_task():
    """Main task logic."""
    print("Running task: {task or 'Custom Script'}")
    # TODO: Implement your custom logic here
    print("Task completed successfully!")


def main():
    print("=" * 40)
    print("     SADIE PYTHON PROGRAM")
    print("=" * 40)
    execute_task()


if __name__ == "__main__":
    main()
'''

    # 2. C++ Templates
    elif lang in ["cpp", "c++"]:
        if any(w in norm_task for w in ["sum", "add"]):
            return '''#include <iostream>

// Sum calculation function
double calculateSum(double a, double b) {
    return a + b;
}

int main() {
    std::cout << "========================================" << std::endl;
    std::cout << "       SADIE C++ SUM CALCULATOR         " << std::endl;
    std::cout << "========================================" << std::endl;

    double num1, num2;
    std::cout << "Enter first number: ";
    if (!(std::cin >> num1)) {
        std::cerr << "Invalid input!" << std::endl;
        return 1;
    }

    std::cout << "Enter second number: ";
    if (!(std::cin >> num2)) {
        std::cerr << "Invalid input!" << std::endl;
        return 1;
    }

    double result = calculateSum(num1, num2);
    std::cout << "\\nResult: " << num1 << " + " << num2 << " = " << result << std::endl;

    return 0;
}
'''
        elif any(w in norm_task for w in ["fibonacci", "fib"]):
            return '''#include <iostream>
#include <vector>

void printFibonacci(int n) {
    if (n <= 0) return;
    long long a = 0, b = 1;
    std::cout << a;
    for (int i = 1; i < n; ++i) {
        std::cout << " -> " << b;
        long long next = a + b;
        a = b;
        b = next;
    }
    std::cout << std::endl;
}

int main() {
    std::cout << "========================================" << std::endl;
    std::cout << "     SADIE C++ FIBONACCI GENERATOR      " << std::endl;
    std::cout << "========================================" << std::endl;

    int count;
    std::cout << "Enter number of terms: ";
    if (std::cin >> count) {
        std::cout << "\\nFibonacci Series (" << count << " terms):\\n";
        printFibonacci(count);
    }
    return 0;
}
'''
        else:
            return '''#include <iostream>

int main() {
    std::cout << "========================================" << std::endl;
    std::cout << "       SADIE C++ PROGRAM                " << std::endl;
    std::cout << "========================================" << std::endl;

    // TODO: Write your custom C++ logic here
    std::cout << "Program executed successfully." << std::endl;

    return 0;
}
'''

    # 3. C Templates
    elif lang == "c":
        return '''#include <stdio.h>

int main() {
    printf("========================================\\n");
    printf("        SADIE C PROGRAM                \\n");
    printf("========================================\\n");

    double a, b;
    printf("Enter first number: ");
    scanf("%lf", &a);
    printf("Enter second number: ");
    scanf("%lf", &b);

    printf("\\nResult: %.2lf + %.2lf = %.2lf\\n", a, b, a + b);
    return 0;
}
'''

    # 4. Java Templates
    elif lang == "java":
        return '''import java.util.Scanner;

public class Main {
    public static double calculateSum(double a, double b) {
        return a + b;
    }

    public static void main(String[] args) {
        System.out.println("========================================");
        System.out.println("       SADIE JAVA APPLICATION           ");
        System.out.println("========================================");

        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter first number: ");
        double num1 = scanner.nextDouble();
        System.out.print("Enter second number: ");
        double num2 = scanner.nextDouble();

        double sum = calculateSum(num1, num2);
        System.out.println("\\nResult: " + num1 + " + " + num2 + " = " + sum);
        scanner.close();
    }
}
'''

    # 5. JavaScript / Node.js
    elif lang in ["javascript", "js"]:
        return '''/**
 * Sum Program in JavaScript / Node.js
 * Generated by SADIE AI Assistant
 */

const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

function calculateSum(a, b) {
    return a + b;
}

console.log("========================================");
console.log("      SADIE JAVASCRIPT PROGRAM          ");
console.log("========================================");

rl.question("Enter first number: ", (n1) => {
    rl.question("Enter second number: ", (n2) => {
        const num1 = parseFloat(n1);
        const num2 = parseFloat(n2);
        const result = calculateSum(num1, num2);
        console.log(`\\n✅ Result: ${num1} + ${num2} = ${result}`);
        rl.close();
    });
});
'''

    # 6. HTML/CSS/JS Web App
    elif lang == "html":
        return f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{task_title}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #0a0f1d 0%, #1e293b 100%);
            color: #f8fafc;
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            margin: 0;
        }}
        .card {{
            background: rgba(30, 41, 59, 0.7);
            backdrop-filter: blur(16px);
            border: 1px solid rgba(0, 229, 255, 0.2);
            padding: 32px;
            border-radius: 16px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.5);
            width: 360px;
            text-align: center;
        }}
        h2 {{ color: #00e5ff; margin-bottom: 20px; }}
        input {{
            width: 100%;
            padding: 10px;
            margin: 8px 0;
            background: rgba(15, 23, 42, 0.8);
            border: 1px solid rgba(255,255,255,0.1);
            color: #fff;
            border-radius: 8px;
            box-sizing: border-box;
        }}
        button {{
            width: 100%;
            padding: 12px;
            margin-top: 12px;
            background: linear-gradient(135deg, #00e5ff, #9d4edd);
            border: none;
            color: #fff;
            font-weight: bold;
            border-radius: 8px;
            cursor: pointer;
        }}
        #result {{ margin-top: 16px; font-size: 1.1rem; color: #00f59b; font-weight: bold; }}
    </style>
</head>
<body>
    <div class="card">
        <h2>{task_title}</h2>
        <input type="number" id="num1" placeholder="Enter first number">
        <input type="number" id="num2" placeholder="Enter second number">
        <button onclick="calculate()">Calculate</button>
        <div id="result"></div>
    </div>

    <script>
        function calculate() {{
            const a = parseFloat(document.getElementById('num1').value) || 0;
            const b = parseFloat(document.getElementById('num2').value) || 0;
            document.getElementById('result').innerText = `Result: ${{a + b}}`;
        }}
    </script>
</body>
</html>
'''

    # Default fallback
    return f'''// {task_title} in {lang.upper()}
// Generated by SADIE AI Assistant

function main() {{
    console.log("Program started for task: {task}");
}}

main();
'''


def create_and_open_in_vscode(
    language: str = "python",
    task_description: str = "sum of two numbers",
    filename: Optional[str] = None,
    custom_code: Optional[str] = None,
    open_editor: bool = True
) -> Dict[str, Any]:
    """
    Create a complete programming file in the specified language and open it in VS Code on Windows.
    
    Args:
        language: Programming language (python, cpp, c, java, javascript, html, etc.)
        task_description: What the program should do (e.g. 'sum of two numbers', 'calculator')
        filename: Optional filename (e.g. 'sum_program.py')
        custom_code: Optional code string. If not provided, generates clean code.
        open_editor: Whether to launch VS Code automatically (default True)
    """
    norm_lang = (language or "python").lower().strip()
    ext = LANGUAGE_EXTENSIONS.get(norm_lang, ".py")

    # Generate clean filename if not specified
    if not filename:
        clean_task = re.sub(r"[^a-zA-Z0-9_]+", "_", task_description.lower()).strip("_")
        if not clean_task:
            clean_task = "program"
        filename = f"{clean_task[:30]}{ext}"
    else:
        if not filename.endswith(ext) and "." not in filename:
            filename = f"{filename}{ext}"

    # Ensure workspace directory exists
    WORKSPACE_DIR.mkdir(parents=True, exist_ok=True)
    file_path = WORKSPACE_DIR / filename

    # Generate code content
    code = custom_code if custom_code else generate_code_content(norm_lang, task_description)

    # Write code to file
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(code)

    # Launch VS Code on Windows
    opened = False
    vscode_exe = get_vscode_executable()

    if open_editor:
        try:
            if vscode_exe:
                subprocess.Popen([vscode_exe, str(file_path)], shell=False)
                opened = True
            else:
                subprocess.Popen(["cmd.exe", "/c", "code", str(file_path)], shell=False)
                opened = True
        except Exception:
            opened = False

    friendly_msg = f"Created '{filename}' in {norm_lang.upper()} and opened it in VS Code on Windows."

    return {
        "success": True,
        "filename": filename,
        "file_path": str(file_path),
        "workspace_dir": str(WORKSPACE_DIR),
        "language": norm_lang,
        "code": code,
        "opened_in_vscode": opened,
        "message": friendly_msg,
        "status_message": friendly_msg
    }
