/**
 * Sum Program in JavaScript / Node.js
 * Generated by SADIE AI Assistant
 */

const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

function calculateSum(a, b) {
    return a + b;
}

console.log("========================================");
console.log("      SADIE JAVASCRIPT PROGRAM          ");
console.log("========================================");

rl.question("Enter first number: ", (n1) => {
    rl.question("Enter second number: ", (n2) => {
        const num1 = parseFloat(n1);
        const num2 = parseFloat(n2);
        const result = calculateSum(num1, num2);
        console.log(`\n✅ Result: ${num1} + ${num2} = ${result}`);
        rl.close();
    });
});
