"""
Sum Calculator Program in Python
Generated by SADIE AI Assistant
"""

def calculate_sum(a: float, b: float) -> float:
    """Returns the sum of two numbers."""
    return a + b


def main():
    print("=" * 40)
    print("        SADIE PYTHON SUM CALCULATOR")
    print("=" * 40)
    
    try:
        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))
        result = calculate_sum(num1, num2)
        print(f"\n✅ Result: {num1} + {num2} = {result}")
    except ValueError:
        print("\n⚠️ Invalid input. Please enter valid numbers.")


if __name__ == "__main__":
    main()
